version: "2"
services:
  pw2:
    privileged: true
    network_mode: host
    environment:
     - PORT=4002
     - HHVM_PORT=8002
     - DB_HOST=127.0.0.1
     - DB_PORT=3002
     - DB_USER=admin
     - DB_DATABASE=pw2
     - DB_PASS=f3d3e61f1c4ddbce127a52c5e18f621194edcd98
     - REDIS_PORT=6002
     - APP_LOG=/var/log/app/pw.log
     - IS_HHVM=#
     - IS_FPM=
    build:
      context: docker-php
    volumes:
      - /data/bimax/pw2/www/app:/app:rw
      - /data/bimax/pw2/www/src:/usr/share/nginx/www:rw
      - /data/bimax/pw2/www/log:/var/log/app:rw

  db2:
    environment:
     - DB_PORT=3002
     - REDIS_PORT=6002
     - DB_PASS=f3d3e61f1c4ddbce127a52c5e18f621194edcd98
     - DB_DATABASES=pw2
     - DB_DATABASE=pw2
     - DB_USER=admin
     - SITE_START=2000
    privileged: true
    network_mode: host
    build:
     context: mariadb
    volumes:
     - /data/bimax/pw2/db/app:/app:rw
     - /data/bimax/pw2/db/data:/var/lib/mysql:rw
     - /data/bimax/pw2/www/src:/usr/share/nginx/www:rw
     - /data/bimax/pw2/db/log:/var/log/mysql:rw
  redis2:
    environment:
     - REDIS_PORT=6002
    privileged: true
    network_mode: host
    build:
     context: redis
    volumes:
     - /data/bimax/pw2/redis/data:/var/lib/redis:rw
     - /data/bimax/pw2/redis/log:/var/log/redis:rw
  
